// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAWOHmWy-2fqTda6Hh7iXg73rCvg5zdr0',
    appId: '1:1056835334984:web:1abe03b148a94817ac797d',
    messagingSenderId: '1056835334984',
    projectId: 'wypozyczalnia-5c338',
    authDomain: 'wypozyczalnia-5c338.firebaseapp.com',
    storageBucket: 'wypozyczalnia-5c338.appspot.com',
    measurementId: 'G-WZSHQGXBJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5PKkn0Yg90Zw0_paA5rOPuFQKfR_Tco',
    appId: '1:1056835334984:android:76f8e1e13df5c46aac797d',
    messagingSenderId: '1056835334984',
    projectId: 'wypozyczalnia-5c338',
    storageBucket: 'wypozyczalnia-5c338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2XgshYOrTPlvH7UjP5Iv3S8lMIflVTu4',
    appId: '1:1056835334984:ios:0b3f27ded60f5cf3ac797d',
    messagingSenderId: '1056835334984',
    projectId: 'wypozyczalnia-5c338',
    storageBucket: 'wypozyczalnia-5c338.appspot.com',
    iosBundleId: 'com.example.wypozyczalnia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2XgshYOrTPlvH7UjP5Iv3S8lMIflVTu4',
    appId: '1:1056835334984:ios:0b3f27ded60f5cf3ac797d',
    messagingSenderId: '1056835334984',
    projectId: 'wypozyczalnia-5c338',
    storageBucket: 'wypozyczalnia-5c338.appspot.com',
    iosBundleId: 'com.example.wypozyczalnia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAWOHmWy-2fqTda6Hh7iXg73rCvg5zdr0',
    appId: '1:1056835334984:web:ee480f3b95e019deac797d',
    messagingSenderId: '1056835334984',
    projectId: 'wypozyczalnia-5c338',
    authDomain: 'wypozyczalnia-5c338.firebaseapp.com',
    storageBucket: 'wypozyczalnia-5c338.appspot.com',
    measurementId: 'G-3HSGLS46H3',
  );

}